- name: Descargar imagen del servidor web desde ACR
  containers.podman.podman_image:
    name: "{{ acr_url }}/{{ web_image }}"

- name: Asegurar que el directorio del host para contenido web exista
  file:
    path: /var/www/html
    state: directory
    mode: '0755'

- name: Agregar archivo index.html de prueba al volumen del host
  copy:
    dest: /var/www/html/index.html
    content: "<html><body><h1>Servidor NGINX con Podman desplegado con Ansible</h1></body></html>"
    mode: '0644'

- name: Ejecutar contenedor del servidor web
  containers.podman.podman_container:
    name: webserver
    image: "{{ acr_url }}/{{ web_image }}"
    state: started
    ports:
      - "80:80"
    volume:
      - "/var/www/html:/usr/share/nginx/html:Z"
