- name: Setup Webserver on Azure VM
  hosts: vm_cp2
  become: true
  vars_files:
    - roles/vm/vars/main.yml
    - acr_credentials.yml
  tasks:
    - name: Run VM configuration
      include_role:
        name: vm

